# ==============================================================================
# Application Main Configuration
# ==============================================================================
spring.application.name=food-delivery-backend

# Active Profile (Set to prod as default active profile)
spring.profiles.active=local